--TRIGGER CREATED TO SEND DETAILS OF NEWLY CREATED TABLES TO A PARTICULAR TABLE (NOTIFICATION TABLE), INCLUDING THE TIME THE TABLE WAS CREATED.


CREATE TRIGGER NOTIFY
ON DATABASE
FOR CREATE_TABLE
AS
BEGIN
	INSERT INTO NOTIFICATION
	VALUES('TABLE CREATED ON' + CAST(GETDATE() AS VARCHAR(20)))
END

CREATE TABLE NOTIFICATION(ID INT IDENTITY(0, 1),
MESSAGE VARCHAR(30))

CREATE TABLE ACCOUNT(BALANCE MONEY,
[DATE] DATETIME) 

CREATE TABLE ACCOUNTS(BALANCE MONEY,
[DATE] DATETIME) 

CREATE TABLE ACCT(BALANCE MONEY,
[DATE] DATETIME) 